### ISSUE TITLE
user auth check list

### ISSUE THREAD

**Issue by mengnlin** [mengnlin/EventMaster#2]
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
- [ ] update spacing of items in the navbar to match eventbrite
- [ ] reduce the size of your logo a bit 
- [ ] remove orange border around your `SessionForm`
- [ ] reduce font size of buttons in `SessionForm`
- [ ] add cursor pointer to buttons on `SessionForm`
- [ ] update the border on the input boxes when they are clicked on
- [ ] increase spacing between "e" logo and "Let's get started"

**Comment by jenkennedy** [comment]
- [ ] Update font size of navbar items (Sign In and Sign Up) to match (they are different sizes)
![Screen Shot 2019-05-09 at 10 12 06 AM](https://user-images.githubusercontent.com/39272166/57472691-ef514700-7242-11e9-8ae1-a1c74aedac69.png)
